#!/usr/bin/env python3
"""
Generate a learning guide PDF from repository analysis.
Uses markdown as intermediate format, then converts to PDF via pandoc.
"""

import os
import sys
import json
import subprocess
from pathlib import Path

def generate_markdown(repo_info, output_path):
    """Generate markdown content for the learning guide."""
    
    md_content = f"""---
title: "{repo_info['name']} - Learning Guide"
author: "Generated by Code Architect"
date: "{repo_info.get('date', 'Today')}"
---

# {repo_info['name']} Learning Guide

## Project Overview

**Purpose:** {repo_info.get('purpose', 'N/A')}

**Tech Stack:** {repo_info.get('tech_stack', 'N/A')}

---

## Architecture

{repo_info.get('architecture', 'Architecture details...')}

---

## Core Components

{repo_info.get('components', 'Component details...')}

---

## Implementation Steps

{repo_info.get('steps', 'Step-by-step guide...')}

---

## Code Examples

{repo_info.get('examples', 'Code examples...')}

---

## Next Steps

{repo_info.get('next_steps', '- Practice implementing features\n- Explore advanced topics\n- Build your own version')}
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    return output_path

def markdown_to_pdf(md_path, pdf_path):
    """Convert markdown to PDF using pandoc."""
    try:
        subprocess.run([
            'pandoc',
            md_path,
            '-o', pdf_path,
            '--pdf-engine=xelatex',
            '-V', 'geometry:margin=1in',
            '--toc',
            '--toc-depth=2'
        ], check=True)
        return pdf_path
    except FileNotFoundError:
        print("Error: pandoc not installed. Install with: apt-get install pandoc texlive-xetex")
        return None
    except subprocess.CalledProcessError as e:
        print(f"Error converting to PDF: {e}")
        return None

def main():
    if len(sys.argv) < 2:
        print("Usage: generate_learning_guide.py <repo_info.json> [output.pdf]")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_pdf = sys.argv[2] if len(sys.argv) > 2 else "learning_guide.pdf"
    
    # Load repo info
    with open(input_file, 'r', encoding='utf-8') as f:
        repo_info = json.load(f)
    
    # Generate markdown
    md_path = output_pdf.replace('.pdf', '.md')
    generate_markdown(repo_info, md_path)
    print(f"✓ Generated markdown: {md_path}")
    
    # Convert to PDF
    pdf_path = markdown_to_pdf(md_path, output_pdf)
    if pdf_path:
        print(f"✓ Generated PDF: {pdf_path}")
    
if __name__ == '__main__':
    main()
